### PR TITLE
refactor: remove test_events_with_untokenised_values from RequirementBasic

### PR DESCRIPTION
**Pull request by artemrys**
There is no need to run test_events_with_untokenised_values test when running
requirement tests. It is needed when running knowledge tests.

### CODE REVIEW

**Comment by nandinivij** [comment]
All the test are failing. As we are not running these tests. We will need to remove it from each requirement functional test https://github.com/artemrys/pytest-splunk-addon/blob/a8f853331e03eb665f638426e7e60a437cb5881c/tests/constants.py#L773

**Comment by arys-splunk** [comment]
> All the Test_Matrix are failing. As we are not running untokenized events test. We will need to remove it from each requirement functional test https://github.com/artemrys/pytest-splunk-addon/blob/a8f853331e03eb665f638426e7e60a437cb5881c/tests/constants.py#L773

Oops, sorry, I removed that line you pointed. Let's wait for the tests to finish.

**Review by nandinivij — APPROVED** [review]

**Review by arys-splunk — APPROVED** [review]

**Pull request merged**
