### PR TITLE
feat!: remove feature cim-field-report generation

### PR DESCRIPTION
**Pull request by dvarasani-crest**
This PR removes the feature of generating cim-field-report.
ref: [ADDON-73385](https://splunk.atlassian.net/browse/ADDON-73385)

NOTE:
- moved unit test file (test_report.py) of cim-compliance report generation test from test_tools folder to test_utilities

### CODE REVIEW

**Comment by kdoroszko-splunk** [comment]
What is the reason of  moving from `tests/unit/tests_standard_lib/test_tools/test_cim_report.py` to `tests/unit/tests_standard_lib/test_utilities/test_cim_report.py`? I can see that tests structure mimics structure of this submodules: https://github.com/splunk/pytest-splunk-addon/tree/main/pytest_splunk_addon.

**Comment by kdoroszko-splunk** [comment]
> @kdoroszko-splunk I have moved that test file to actually align that with the submodules. `test_report.py` tests for cim-report generation which is for function generate_report of `standard_lib/utilities/junit_parser.py::generate_report()`.

Right, thanks for clarifying.

**Comment by mkolasinski-splunk** [comment]
@dvarasani-crest is `!` sign in PR title intentional?

**Comment by dvarasani-crest** [comment]
> @dvarasani-crest is `!` sign in PR title intentional? Consider changing base branch to `release/v5.4.0`
> 
> Beside above, LGTM!

@mkolasinski-splunk I have added ! to indicate this PR as a breaking change. Also, since this PR contains a BREAKING change commit, do you still think we need to rebase it to release/5.4.0? because merging this commit to release/5.4.0 would lead to release v6.0.0 when we merge release/5.4.0 to main.
Let me know if we do not want to consider this as a BREAKING change.

**Comment by mkolasinski-splunk** [comment]
> > @dvarasani-crest is `!` sign in PR title intentional? Consider changing base branch to `release/v5.4.0`
> > Beside above, LGTM!
> 
> @mkolasinski-splunk I have added ! to indicate this PR as a breaking change. Also, since this PR contains a BREAKING change commit, do you still think we need to rebase it to release/5.4.0? because merging this commit to release/5.4.0 would lead to release v6.0.0 when we merge release/5.4.0 to main. Let me know if we do not want to consider this as a BREAKING change.

You are right - let's keep it this way. Regarding base branch - I think we can merge it to develop as there are being aggregated changes for v6.0.0 release as far as I can see: https://github.com/splunk/pytest-splunk-addon/pull/871

**Comment by dvarasani-crest** [comment]
> > > @dvarasani-crest is `!` sign in PR title intentional? Consider changing base branch to `release/v5.4.0`
> > > Beside above, LGTM!
> > 
> > 
> > @mkolasinski-splunk I have added ! to indicate this PR as a breaking change. Also, since this PR contains a BREAKING change commit, do you still think we need to rebase it to release/5.4.0? because merging this commit to release/5.4.0 would lead to release v6.0.0 when we merge release/5.4.0 to main. Let me know if we do not want to consider this as a BREAKING change.
> 
> You are right - let's keep it this way. Regarding base branch - I think we can merge it to develop as there are being aggregated changes for v6.0.0 release as far as I can see: #871

Updated base branch to develop.

**Review by harshilgajera-crest — APPROVED** [review]

**Review by mkolasinski-splunk — APPROVED** [review]

**Pull request merged**
