### PR TITLE
feat: Req_test for syslog sources with event ingestion via SC4S

### PR DESCRIPTION
**Pull request by nandinivij**
Feature add:

- Requirement test event ingestion is done via SC4S.

- As logs are ingested via SC4S “extract_regex_transforms()” “extract_sourcetype()” functions are no longer needed to determine source type of event using transforms.conf
-  In the previous version the complete event was searched for via Splunk search but as now we use SC4S, the event ingested is processed and does not contain HEADER. Syslog Header is removed  from search by function strip_syslog_header()

- Change location of input requirement files from package/requirement_files -> tests/requirement_tests/  as package folder gets released and it cannot contain logs.

- Location of files and whether to run the requirement test or not will be given by the “requirement-test” parameter in pytest.ini file

	``—requirement-test=tests/requirement_files``

- extract_transport_tag() function added to determine the transport type of event and ingest data if it is syslog. 

``` <transport type="syslog" />```

- No ingestion for events that do not have a CIM tag

- Better error message(source_type, mismatched fields added for the event failure):
Sample error:
```E       AssertionError: Issue with the field extraction.
E         search=search index=* RT_UTM\: WEBFILTER_URL_BLOCKED\: WebFilter\: ACTION\="URL Blocked" 10.0.0.1\(1111\)\-\>10.0.0.2\(2222\) CATEGORY\="sample_category" RE\ASON\="dummy_reason" PROFILE\="dummy_profile" URL\=dummy_url OBJ\=dummy_obj username dummy_user roles dummy_user_roles |fields * 
E          Field_extraction_check: False 
E          Key value not extracted in splunk event: {'category': 'sample_category'} 
E          Mismatched key value: {'category': 'sample_category dummy_sub_category'}
E          source type of ingested event: juniper:junos:firewall 
E         
E       assert False
```

- Fixed unit test failures due to code change

### CODE REVIEW

**Comment by kkania-splunk** [comment]
Im working on certification new add-ons and looking forward to requirement tests functionality. Some add-ons to work require to ingest data with specific source and sourcetype (hardcoded in add-on). Will ingesting with specific source and sourcetype be supported with requirement tests?

**Comment by nandinivij** [comment]
> Im working on certification new add-ons and looking forward to requirement tests functionality. Some add-ons to work require to ingest data with specific source and sourcetype (hardcoded in add-on). Will ingesting with specific source and sourcetype be supported with requirement tests?

We are slowly gonna add inputs based on the transport type for eg: mod_input/ UF and windows input.
And some of them will need us to hardcode source and source type. Our previous version of req_test was using event_ingester’s HEC Event Ingestor for syslog events which provides you a way to ingest data with hardcoded source and source type.
https://pytest-splunk-addon.readthedocs.io/en/latest/api_reference/event_ingestion.html. If that is something you are looking for

**Review by rfaircloth-splunk — APPROVED** [review]

**Review by drnkllr — APPROVED** [review]
Excellent progress!

**Pull request merged**
