### PR TITLE
Sample generation - code cleanup

### PR DESCRIPTION
**Pull request by wmazur-splunk**
It started with "I'll just remove that static variable" and ended with significant refactoring. Feel free to "freeze it" until next major release if you are afraid it can be a breaking change. 

The change could be much wider, but I leave it for future

### CODE REVIEW

**Comment by uoboda-splunk** [comment]
Please fix pre-commit

**Comment by uoboda-splunk** [comment]
Lets merge these changes to develop and next test with some TA

**Comment by artemrys** [comment]
It's a refactoring which I am afraid to merge since the impact of this change is not clear to me. I'd rather move it to draft.

@wmazur-splunk if you want to work on this PR - please feel free, we will support you. It would be nice to split this PR into some smaller ones and merge them one by one.

**Comment by wmazur-splunk** [comment]
Feel free to close the PR, I do not remember what was done in this PR. Definitely some refactoring - but how was it tested? I don't know.

**Pull request closed without merging**
