### PR TITLE
fix: do not log .conf parser warnings from all workers

### PR DESCRIPTION
**Pull request by harshilgajera-crest**
When tests are ran with multiple workers, duplicate logging is observed because every workers logs the warning.
This PR fixes that.

### CODE REVIEW

**Comment by harshilgajera-crest** [comment]
> Please extract this logic in a helper function, it's been used several times already across the codebase.

Done

**Review by mkolasinski-splunk — COMMENTED** [review]
I'd consider creating separate utils file with check_first_worker() instead of having delayed imports. @artemrys wdyt?

**Comment by harshilgajera-crest** [comment]
> I'd consider creating separate utils file with check_first_worker() instead of having delayed imports. @artemrys wdyt?

I thought the same but because it was only one small function i thought it was not needed, but we can do that.

**Review by artemrys — APPROVED** [review]

**Pull request merged**
